"""
Django settings for FaceDetection project.

<<<<<<< HEAD
Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
=======
Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from corsheaders.defaults import default_headers
>>>>>>> 96823c6827b23b7a7529a75e690ef3a64981c7b8

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

<<<<<<< HEAD

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1%ky8zy!=!0q5oj$l-mrtz6df2x7hskh_$!06ojj089h%y^-%1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['MohamedBENIAICH.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
=======
# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-cl_20==(ncwy7(7-j7)jr$@kg1&#eq1tyb)kc+tdd@hz4ozg)k'
ALLOWED_HOSTS = ['*']
DEBUG = False

# Application definition
INSTALLED_APPS = [
    'channels',
>>>>>>> 96823c6827b23b7a7529a75e690ef3a64981c7b8
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
]

MIDDLEWARE = [
=======
    'corsheaders',
    'django_extensions',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
>>>>>>> 96823c6827b23b7a7529a75e690ef3a64981c7b8
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
<<<<<<< HEAD
]

ROOT_URLCONF = 'FaceDetection.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
=======
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://192.168.95.204:8000",
]

CORS_ALLOW_HEADERS = list(default_headers) + [
    "content-type",
    "authorization",
    "sec-websocket-protocol",
    "sec-websocket-extensions",
]

CSP_CONNECT_SRC = (
    "'self'",
    "ws://192.168.95.204:8000",  # Allow WebSocket (ws://) from this IP and port
    "wss://192.168.95.204:8000",  # Allow Secure WebSocket
)


ROOT_URLCONF = 'FaceDetection.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
>>>>>>> 96823c6827b23b7a7529a75e690ef3a64981c7b8
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FaceDetection.wsgi.application'
<<<<<<< HEAD


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

=======
ASGI_APPLICATION = 'FaceDetection.asgi.application'

# Database
>>>>>>> 96823c6827b23b7a7529a75e690ef3a64981c7b8
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

<<<<<<< HEAD

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

=======
# Password validation
>>>>>>> 96823c6827b23b7a7529a75e690ef3a64981c7b8
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

<<<<<<< HEAD

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# default static files settings for PythonAnywhere.
# see https://help.pythonanywhere.com/pages/DjangoStaticFiles for more info
MEDIA_ROOT = '/home/MohamedBENIAICH/FaceDetection/media'
MEDIA_URL = '/media/'
STATIC_ROOT = '/home/MohamedBENIAICH/FaceDetection/static'
STATIC_URL = '/static/'
=======
# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
>>>>>>> 96823c6827b23b7a7529a75e690ef3a64981c7b8
